# .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "114358259112430616238"
private_key_id = "bf7a124d46e7485c746d8514ff441bb6e0517cff"
private_key = "9afa045bcd1440bc7b7898b935873f4bf1f596b9	"
client_email = "lake-winni-service-account@lake-winni.iam.gserviceaccount.com"
client_id = "114358259112430616238"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "xxx"